name = "grotohackers"
version = "1.0.0"

[dependencies]
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleamy_structures = ">= 1.2.0 and < 2.0.0"
glisten = ">= 8.0.3 and < 9.0.0"
grammy = { git = "https://github.com/jtdowney/grammy.git", ref = "update-deps" }
logging = ">= 1.3.0 and < 2.0.0"
mug = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
unitest = ">= 1.0.0 and < 2.0.0"
