name = "grotohackers"
version = "1.0.0"

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glisten = ">= 8.0.3 and < 9.0.0"

[dev-dependencies]
unitest = ">= 1.0.0 and < 2.0.0"
